baseURL = "https://syban75.github.io/blog/"
locale = "ko-kr"
title = "잡학사전"

theme = "hugo-book"

[params]
BookSection = "docs"
mainSections = ["docs"]

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = true

[pagination]
pagerSize = 10

